<a href="https://colab.research.google.com/github/przemyslawtutur/learning2/blob/main/100_przemyslaw_tutur_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#### 1. Import the numpy package under the name `np` (★☆☆)
import numpy as np

In [3]:
#### 2. Print the numpy version and the configuration (★☆☆)
print(np.__version__)
print(np.show_config())
#print(np.__config__)

1.23.5
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

In [4]:
# 3. Create a null vector of size 10 (★☆☆)
null_vector_size_10 = np.zeros(10)

In [6]:
# 4. How to find the memory size of any array (★☆☆)
array = np.zeros((10, 10))
memory_size = array.size * array.itemsize
memory_size

800

In [19]:
# 5. How to get the documentation of the numpy add function from the command line? (★☆☆)
numpy.info(numpy.add)

UsageError: Line magic function `%numpy.info(numpy.add)` not found.


In [11]:
%ls /bin/ | grep python

python3@
python3.10*
python3.10-config@
python3-config@
x86_64-linux-gnu-python3.10-config*
x86_64-linux-gnu-python3-config@


In [23]:
#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
v = np.arange(10)
v[4] = 1
v

array([0, 1, 2, 3, 1, 5, 6, 7, 8, 9])

In [25]:
#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)
v = np.arange(10, 50)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [27]:
#### 8. Reverse a vector (first element becomes last) (★☆☆)
rv = np.arange(0,10)
rv = rv[::-1]
rv

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [28]:
#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
m = np.arange(0, 9).reshape(3,3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
nz = np.nonzero([1,2,0,0,4,0])
nz

(array([0, 1, 4]),)

In [30]:
#### 11. Create a 3x3 identity matrix (★☆☆)

im = np.eye(3,3)
im

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
# Create a 3x3x3 array with random values (★☆☆)
ra = np.random.random(27).reshape(3,3,3)
ra

array([[[0.61550803, 0.20145467, 0.65801381],
        [0.03444605, 0.04304555, 0.39372463],
        [0.74325915, 0.61753542, 0.613417  ]],

       [[0.36877605, 0.90298807, 0.59341573],
        [0.63654892, 0.63335927, 0.01738541],
        [0.07769588, 0.87360506, 0.52563442]],

       [[0.58707084, 0.67580557, 0.22948371],
        [0.88434289, 0.61833037, 0.26106971],
        [0.45659568, 0.07083659, 0.63054186]]])

In [35]:
# Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
ar = np.random.random((10, 10))
print(np.max(ar))
print(np.min(ar))

ar.min(), ar.max()


0.9880334366860835
0.004295898377367657


(0.004295898377367657, 0.9880334366860835)

In [38]:
#### 14. Create a random vector of size 30 and find the mean value (★☆☆)
print(np.mean(np.random.random(30)))
print(np.random.random(30).mean())

0.464077541355341
0.6416607978239697


In [39]:
#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
o = np.ones((10, 10))
o[1:-1, 1:-1] = 0
o

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [40]:
#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
a = np.ones((5,5))
a = np.pad(a, pad_width=1, mode='constant', constant_values=0)
a

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [41]:
Z = np.ones((5,5))
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [43]:
#### 17. What is the result of the following expression? (★☆☆)
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False
False


In [48]:
#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
e = np.diag([0, 1, 2, 3, 4])
e

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [45]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [52]:
#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

x = np.zeros((8,8))
x[1::2, ::2] = 1
x[0::2, 1::2] = 1
x

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [53]:
#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [57]:
#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
Z = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [63]:
#### 22. Normalize a 5x5 random matrix (★☆☆)

rm = np.random.random((5, 5))
print(rm)
rm = (rm - rm.mean())/(np.std(rm))
print(rm)

[[0.65600437 0.50940543 0.06362208 0.44665366 0.96446629]
 [0.44671434 0.79517024 0.98963273 0.64820539 0.06449846]
 [0.16530951 0.8392149  0.6037765  0.26447754 0.24504808]
 [0.51645058 0.46051076 0.02607673 0.96901369 0.06436274]
 [0.99170317 0.05898398 0.65287673 0.25638933 0.64034787]]
[[ 0.51299603  0.05004922 -1.35769616 -0.14811546  1.48709217]
 [-0.14792382  0.95246986  1.56656562  0.48836754 -1.35492863]
 [-1.03657603  1.0915591   0.34806494 -0.72341194 -0.7847685 ]
 [ 0.07229721 -0.10435593 -1.47626113  1.50145247 -1.3553572 ]
 [ 1.5731039  -1.37234287  0.50311921 -0.74895379  0.46355416]]


In [65]:
#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
d = np.ubyte
k = np.array(4, dtype=np.ubyte)
k

array(4, dtype=uint8)

In [67]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [68]:
color = np.dtype([("r", np.ubyte), ("g", np.ubyte), ("b", np.ubyte), ("a", np.ubyte)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [71]:
#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
multi = np.dot(np.ones((5,3)), np.ones((3, 2)))
multi

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [76]:
multi = np.cross(np.ones((5,3)), np.ones((5, 2)))
multi

array([[-1.,  1.,  0.],
       [-1.,  1.,  0.],
       [-1.,  1.,  0.],
       [-1.,  1.,  0.],
       [-1.,  1.,  0.]])

In [78]:
#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr[3:9] *= (-1)
arr

array([ 1,  2,  3, -4, -5, -6, -7, -8, -9, 10])

In [79]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [80]:
#### 26. What is the output of the following script? (★☆☆)

In [81]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [83]:
Z = np.ones((3,3))
Z**Z

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [84]:
Z = np.ones((3,3))

In [85]:
2 << Z >> 2

TypeError: ignored

In [86]:
Z = np.ones((3,3))
Z <- Z

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [87]:
Z = np.ones((3,3))

In [88]:
1j * Z

array([[0.+1.j, 0.+1.j, 0.+1.j],
       [0.+1.j, 0.+1.j, 0.+1.j],
       [0.+1.j, 0.+1.j, 0.+1.j]])

In [89]:
Z = np.ones((3, 2))
Z/1/1

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [90]:
Z = np.ones((3,4))
Z<Z>Z

ValueError: ignored

In [91]:
#### 28. What are the result of the following expressions? (★☆☆)

In [92]:
np.array(0) / np.array(0)


<ipython-input-92-3585dcb7ab9b>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


nan

In [93]:
np.array(0) // np.array(0)

<ipython-input-93-4764261090d0>:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [94]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

In [95]:
np.array([np.nan])

array([nan])

In [96]:
np.array([np.nan]).astype(int)

array([-9223372036854775808])

In [97]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

In [98]:
#### 29. How to round away from zero a float array ? (★☆☆)

In [101]:
Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

[  9.   1.  -7.   4.  -4.   5.  -8. -10. -10. -10.]


In [102]:
#### 30. How to find common values between two arrays? (★☆☆)

In [104]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(Z1)
print(Z2)
print(np.intersect1d(Z1, Z2))

[0 9 1 0 1 4 8 7 2 6]
[6 3 6 6 7 5 3 5 1 4]
[1 4 6 7]


In [106]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0
print(Z)
# Back to sanity
_ = np.seterr(**defaults)

[inf]


In [109]:
#### 32. Is the following expressions true? (★☆☆)
np.sqrt(-1) == np.emath.sqrt(-1)
np.sqrt(-1)
np.emath.sqrt(-1)

<ipython-input-109-334095658bf3>:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)
<ipython-input-109-334095658bf3>:3: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1)


1j

In [112]:
#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)
yesterday = np.datetime64('today') - np.timedelta64(1)
today = np.datetime64('today')
tomorrow = np.datetime64('today') + np.timedelta64(1)
print(yesterday)
print(today)
print(tomorrow)

2023-10-09
2023-10-10
2023-10-11


In [113]:
#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)
date_array = np.arange("2016-07", "2016-08", dtype='datetime64[D]')
print(date_array)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [117]:
#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A, B, out=B)
np.divide(-A, 2, out=A)
A, B


(array([-0.5, -0.5, -0.5]), array([3., 3., 3.]))

In [118]:
np.multiply(A, B, out=A)

array([-1.5, -1.5, -1.5])

In [119]:
#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [123]:
ra = np.random.uniform(0, 10, 10)
ra

array([5.78941434, 5.85650163, 2.92466928, 0.36928624, 5.16443283,
       5.02573578, 1.0540538 , 6.43948696, 0.70491564, 8.73163851])

In [125]:
np.floor(ra)

array([5., 5., 2., 0., 5., 5., 1., 6., 0., 8.])

In [127]:
ra // 1

array([5., 5., 2., 0., 5., 5., 1., 6., 0., 8.])

In [129]:
ra.astype(int)

array([5, 5, 2, 0, 5, 5, 1, 6, 0, 8])

In [130]:
np.trunc(ra)

array([5., 5., 2., 0., 5., 5., 1., 6., 0., 8.])

In [131]:
#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [137]:
m = np.tile(array([0, 1, 2, 3, 4]), (5, 1))
m

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [139]:
#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

def generator_f():
  for x in range(10):
    yield x

ag = np.fromiter(generator_f(), dtype=float, count=-1)
print(ag)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [140]:
#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [143]:
v = np.linspace(0, 1, 11)[1:-1]
v

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [144]:
#### 40. Create a random vector of size 10 and sort it (★★☆)

In [149]:
sv = np.random.random(10)

np.sort(sv)

array([0.0613029 , 0.12871953, 0.34961039, 0.40867175, 0.55193135,
       0.68798167, 0.94027419, 0.94634988, 0.95549367, 0.95683519])

In [150]:
#### 41. How to sum a small array faster than np.sum? (★★☆)

In [151]:
a = np.arange(10)

In [152]:
np.add.reduce(a)

45

In [154]:
#### 42. Consider two random array A and B, check if they are equal (★★☆)
A = np.random.random(10)
B = np.random.random(10)
np.allclose(A, B)
np.array_equal(A, B)

False

In [155]:
#### 43. Make an array immutable (read-only) (★★☆)

In [156]:
a = np.zeros(5)
a.flags.writeable = False
a[0] = 10

ValueError: ignored

In [158]:
#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
v = np.random.random((10, 2))
v

array([[0.5746162 , 0.50837995],
       [0.58893575, 0.44181694],
       [0.57075391, 0.57969525],
       [0.77109709, 0.71784897],
       [0.70212969, 0.04301897],
       [0.91119083, 0.38783516],
       [0.20057289, 0.72494017],
       [0.8612446 , 0.9896544 ],
       [0.35820731, 0.73763993],
       [0.72966658, 0.32705301]])

In [159]:
A = v[:,0]
B = v[:,1]
R = np.sqrt(A**2 + B**2)
T = np.arctan2(A, B)

In [160]:
print(R)
print(T)

[0.76722484 0.73623877 0.81351497 1.0535169  0.70344632 0.99029533
 0.75217533 1.31192915 0.82001533 0.79961052]
[0.84648226 0.92717012 0.77762627 0.82114522 1.50960356 1.16838753
 0.26992286 0.71613216 0.45207166 1.14942151]


In [162]:
#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
v = np.random.random(10)
v[v.argmax()] = 0
v

array([0.        , 0.28936498, 0.22882791, 0.62614577, 0.21391205,
       0.95085057, 0.70085934, 0.57791077, 0.40833768, 0.07071519])

In [163]:
#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [164]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [4]:
import numpy as np
a = np.zeros((5,5), [('x', float), ('y', float)])
a['x'], a['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))

print(a)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [9]:
a = np.ones((2, 2, 2), [("x", float), ("y", float), ("z", float)])
a['x'] = np.linspace(0, 10, 2)
a['y'] = np.linspace(0, 10, 2)
a['z'] = np.linspace(0, 4, 2)
print(a)

[[[( 0.,  0., 0.) (10., 10., 4.)]
  [( 0.,  0., 0.) (10., 10., 4.)]]

 [[( 0.,  0., 0.) (10., 10., 4.)]
  [( 0.,  0., 0.) (10., 10., 4.)]]]


In [10]:
#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


In [15]:
#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

for k in [np.int8, np.int32, np.int64]:
   print(np.iinfo(k).min)
   print(np.iinfo(k).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807


In [17]:
#### 49. How to print all the values of an array? (★★☆)

# np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [20]:
#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)
Z = np.arange(100)
v = np.random.uniform(0,100)
print(v)
index = (np.abs(Z-v)).argmin()
print(Z)
print(v)
print(Z[index])

93.37645369641142
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
93.37645369641142
93


In [23]:
v = np.random.uniform(0, 100)
a = np.arange(100)

index = np.abs(a-v).argmin()
print(a[index])

3


In [24]:
#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

a = np.zeros(shape=10, dtype=[('position', [('x', float, 1), ('y', float, 1)]),
                               ('rgb', [('r', float, 1), ('g', float, 1),('b', float, 1)])])
print(a)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-24-693415b9a260>:3: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  a = np.zeros(shape=10, dtype=[('position', [('x', float, 1), ('y', float, 1)]),


In [2]:
#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)
import numpy as np

rv = np.random.random((100, 2))
X, Y = np.atleast_2d(rv[:,0], rv[:,1])
D = np.sqrt((X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.71785704 0.36581798 ... 0.61010363 0.53434025 0.84143016]
 [0.71785704 0.         0.35208975 ... 0.12557977 0.18510271 0.26754575]
 [0.36581798 0.35208975 0.         ... 0.24762641 0.16895661 0.50276937]
 ...
 [0.61010363 0.12557977 0.24762641 ... 0.         0.08278619 0.27543015]
 [0.53434025 0.18510271 0.16895661 ... 0.08278619 0.         0.3553612 ]
 [0.84143016 0.26754575 0.50276937 ... 0.27543015 0.3553612  0.        ]]


In [5]:
#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?
v = (np.random.rand(10)*100).astype(np.float32)
print(v)
n = v.view(np.int32)
print(n)

[75.60089  88.444176 97.87895  36.54271  82.219185 60.079357 49.237267
 86.4554   66.65577  96.77009 ]
[1117205416 1118888811 1120125446 1108487100 1118072889 1114657091
 1111814902 1118628138 1116032961 1119980105]


In [ ]:
#### 54. How to read the following file? (★★☆)
#```
#1, 2, 3, 4, 5
#6,  ,  , 7, 8
# ,  , 9,10,11
#```

In [6]:
from io import StringIO

s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')

z = np.genfromtxt(s, delimiter=',', dtype=np.int)
z

<ipython-input-6-7353bee850c5>:10: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  z = np.genfromtxt(s, delimiter=',', dtype=np.int)


array([[ 1,  2,  3,  4,  5],
       [ 6, -1, -1,  7,  8],
       [-1, -1,  9, 10, 11]])